-- AlterTable
ALTER TABLE `stock` ADD COLUMN `lastMonthCarry` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `monthlyIn` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `monthlyOut` INTEGER NOT NULL DEFAULT 0,
    MODIFY `totalIn` INTEGER NOT NULL DEFAULT 0,
    MODIFY `totalOut` INTEGER NOT NULL DEFAULT 0,
    MODIFY `remaining` INTEGER NOT NULL DEFAULT 0,
    MODIFY `stockValue` DOUBLE NOT NULL DEFAULT 0.0;
