import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { SessionProvider } from "next-auth/react";
import SessionProviderWrapper from "./provider/Provider";
import { SessionContextProvider } from "./provider/SessionContext";
import Profile from "./component/profile";
import "handsontable/dist/handsontable.full.css";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import SideBar from "./component/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body className={`${inter.className} h-full`}>
        <SessionProviderWrapper>
          <SessionContextProvider>
            <Theme className="h-full">
              <main className="h-full ">
                <div className="flex h-full">
                  <div className="w-full">{children}</div>
                </div>
              </main>
            </Theme>
          </SessionContextProvider>
        </SessionProviderWrapper>
        <Toaster />
      </body>
    </html>
  );
}
